<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MKapal;

class MKapalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kapals = [
            [
                'm_kapal_id' => 1,
                'nama_kapal' => 'Kapal Patroli 001',
                'code_kapal' => 'KAPAL-001',
                'm_upt_code' => '000',
                'bobot' => 50.00,
                'panjang' => 20.00,
                'tinggi' => 5.00,
                'lebar' => 8.00,
                'main_engine' => 'YANMAR 6GH-UTE',
                'jml_main_engine' => 2,
                'pk_main_engine' => '500 HP',
                'aux_engine_utama' => 'MITSUBISHI 4D 30',
                'jml_aux_engine_utama' => 1,
                'pk_aux_engine_utama' => '100 HP',
                'gerak_engine' => 'Diesel',
                'aux_engine_emergency' => 'Emergency Engine',
                'galangan_pembuat' => 'PT. Galangan Indonesia',
                'kapasitas_tangki' => '5000',
                'jml_tangki' => 2,
                'tahun_buat' => 2020,
                'jml_abk' => 10,
                'nama_nakoda' => 'John Doe',
                'nip_nakoda' => '123456789012345678',
                'jabatan_nakoda' => 'Nakhoda',
                'pangkat_nakoda' => 'III/c',
                'golongan_nakoda' => 'III/c',
                'gambar_kapal' => 'kapal-001.jpg',
                'lampiran_kapal' => 'lampiran-001.pdf',
                'nama_kkm' => 'Jane Doe',
                'nip_kkm' => '987654321098765432',
                'jabatan_kkm' => 'KKM',
                'pangkat_kkm' => 'III/b',
                'golongan_kkm' => 'III/b',
                'date_insert' => now(),
                'user_insert' => 'admin',
                'date_update' => now(),
                'user_update' => 'admin'
            ],
            [
                'm_kapal_id' => 2,
                'nama_kapal' => 'Kapal Patroli 002',
                'code_kapal' => 'KAPAL-002',
                'm_upt_code' => '000',
                'bobot' => 45.00,
                'panjang' => 18.00,
                'tinggi' => 4.50,
                'lebar' => 7.50,
                'main_engine' => 'YANMAR 6AY-WGT',
                'jml_main_engine' => 2,
                'pk_main_engine' => '450 HP',
                'aux_engine_utama' => 'MITSUBISHI 4D 30',
                'jml_aux_engine_utama' => 1,
                'pk_aux_engine_utama' => '90 HP',
                'gerak_engine' => 'Diesel',
                'aux_engine_emergency' => 'Emergency Engine',
                'galangan_pembuat' => 'PT. Galangan Indonesia',
                'kapasitas_tangki' => '4000',
                'jml_tangki' => 2,
                'tahun_buat' => 2019,
                'jml_abk' => 8,
                'nama_nakoda' => 'Ahmad Rahman',
                'nip_nakoda' => '234567890123456789',
                'jabatan_nakoda' => 'Nakhoda',
                'pangkat_nakoda' => 'IV/a',
                'golongan_nakoda' => 'IV/a',
                'gambar_kapal' => 'kapal-002.jpg',
                'lampiran_kapal' => 'lampiran-002.pdf',
                'nama_kkm' => 'Siti Nurhaliza',
                'nip_kkm' => '345678901234567890',
                'jabatan_kkm' => 'KKM',
                'pangkat_kkm' => 'III/d',
                'golongan_kkm' => 'III/d',
                'date_insert' => now(),
                'user_insert' => 'admin',
                'date_update' => now(),
                'user_update' => 'admin'
            ],
            [
                'm_kapal_id' => 3,
                'nama_kapal' => 'Kapal Patroli 003',
                'code_kapal' => 'KAPAL-003',
                'm_upt_code' => '000',
                'bobot' => 55.00,
                'panjang' => 22.00,
                'tinggi' => 5.50,
                'lebar' => 8.50,
                'main_engine' => 'YANMAR 6AY-WGT',
                'jml_main_engine' => 2,
                'pk_main_engine' => '550 HP',
                'aux_engine_utama' => 'MITSUBISHI 4D 30',
                'jml_aux_engine_utama' => 1,
                'pk_aux_engine_utama' => '110 HP',
                'gerak_engine' => 'Diesel',
                'aux_engine_emergency' => 'Emergency Engine',
                'galangan_pembuat' => 'PT. Galangan Indonesia',
                'kapasitas_tangki' => '6000',
                'jml_tangki' => 2,
                'tahun_buat' => 2021,
                'jml_abk' => 12,
                'nama_nakoda' => 'Maria Santos',
                'nip_nakoda' => '567890123456789012',
                'jabatan_nakoda' => 'Nakhoda',
                'pangkat_nakoda' => 'III/d',
                'golongan_nakoda' => 'III/d',
                'gambar_kapal' => 'kapal-003.jpg',
                'lampiran_kapal' => 'lampiran-003.pdf',
                'nama_kkm' => 'Carlos Rodriguez',
                'nip_kkm' => '678901234567890123',
                'jabatan_kkm' => 'KKM',
                'pangkat_kkm' => 'III/c',
                'golongan_kkm' => 'III/c',
                'date_insert' => now(),
                'user_insert' => 'admin',
                'date_update' => now(),
                'user_update' => 'admin'
            ],
            [
                'm_kapal_id' => 4,
                'nama_kapal' => 'Kapal Patroli 004',
                'code_kapal' => 'KAPAL-004',
                'm_upt_code' => '000',
                'bobot' => 40.00,
                'panjang' => 16.00,
                'tinggi' => 4.00,
                'lebar' => 7.00,
                'main_engine' => 'YANMAR 6GH-UTE',
                'jml_main_engine' => 2,
                'pk_main_engine' => '400 HP',
                'aux_engine_utama' => 'MITSUBISHI 4D 30',
                'jml_aux_engine_utama' => 1,
                'pk_aux_engine_utama' => '80 HP',
                'gerak_engine' => 'Diesel',
                'aux_engine_emergency' => 'Emergency Engine',
                'galangan_pembuat' => 'PT. Galangan Indonesia',
                'kapasitas_tangki' => '3000',
                'jml_tangki' => 2,
                'tahun_buat' => 2018,
                'jml_abk' => 6,
                'nama_nakoda' => 'David Lee',
                'nip_nakoda' => '123450987654321098',
                'jabatan_nakoda' => 'Nakhoda',
                'pangkat_nakoda' => 'III/c',
                'golongan_nakoda' => 'III/c',
                'gambar_kapal' => 'kapal-004.jpg',
                'lampiran_kapal' => 'lampiran-004.pdf',
                'nama_kkm' => 'Lisa Chen',
                'nip_kkm' => '234561098765432109',
                'jabatan_kkm' => 'KKM',
                'pangkat_kkm' => 'III/b',
                'golongan_kkm' => 'III/b',
                'date_insert' => now(),
                'user_insert' => 'admin',
                'date_update' => now(),
                'user_update' => 'admin'
            ],
            [
                'm_kapal_id' => 5,
                'nama_kapal' => 'Kapal Patroli 005',
                'code_kapal' => 'KAPAL-005',
                'm_upt_code' => '000',
                'bobot' => 60.00,
                'panjang' => 24.00,
                'tinggi' => 6.00,
                'lebar' => 9.00,
                'main_engine' => 'YANMAR 6AY-WGT',
                'jml_main_engine' => 2,
                'pk_main_engine' => '600 HP',
                'aux_engine_utama' => 'MITSUBISHI 4D 30',
                'jml_aux_engine_utama' => 1,
                'pk_aux_engine_utama' => '120 HP',
                'gerak_engine' => 'Diesel',
                'aux_engine_emergency' => 'Emergency Engine',
                'galangan_pembuat' => 'PT. Galangan Indonesia',
                'kapasitas_tangki' => '7000',
                'jml_tangki' => 2,
                'tahun_buat' => 2022,
                'jml_abk' => 14,
                'nama_nakoda' => 'Abdul Rahman',
                'nip_nakoda' => '789016543210987654',
                'jabatan_nakoda' => 'Nakhoda',
                'pangkat_nakoda' => 'III/d',
                'golongan_nakoda' => 'III/d',
                'gambar_kapal' => 'kapal-005.jpg',
                'lampiran_kapal' => 'lampiran-005.pdf',
                'nama_kkm' => 'Fatimah Zahra',
                'nip_kkm' => '890127654321098765',
                'jabatan_kkm' => 'KKM',
                'pangkat_kkm' => 'III/c',
                'golongan_kkm' => 'III/c',
                'date_insert' => now(),
                'user_insert' => 'admin',
                'date_update' => now(),
                'user_update' => 'admin'
            ]
        ];

        foreach ($kapals as $kapal) {
            MKapal::updateOrCreate(
                ['m_kapal_id' => $kapal['m_kapal_id']],
                $kapal
            );
        }
    }
}
