<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MUptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $upts = [
            [
                'm_upt_id' => 1,
                'nama' => 'Kantor Pusat PSDKP',
                'code' => '000',
                'alamat1' => 'Jalan Medan Merdeka Timur No. 16 Gedung Mina Bahari IV Lt 12 Jakarta Pusat 10110',
                'alamat2' => 'Kotak Pos 4130 JKP Telepon (021) 3519070 (Hunting) Faksimil (021) 3520346',
                'alamat3' => 'Website : www.djpsdkp.kkp.go.id E-mail : ditjenpsdkp@kkp.go.id',
                'kota' => 'JAKARTA',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Ir Suharta M.Si',
                'nip_petugas' => '196510221994031001',
                'jabatan_petugas' => 'Direktur Pemantauan dan Operas',
                'pangkat_petugas' => '-',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-06-19 07:11:39',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 2,
                'nama' => 'PANGKALAN PSDKP LAMPULO',
                'code' => '001',
                'alamat1' => 'Jalan Indra Budiman No. 12 Lampulo Banda Aceh 23127',
                'alamat2' => 'Telepon (0651) 6303980 Fax (0651) 6303149',
                'alamat3' => 'Website : www.djpsdkp.kkp.go.id E-mail : psdkp.lampulo@kkp.go.id',
                'kota' => 'Banda Aceh',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Basri, A.Pi, M.Si',
                'nip_petugas' => '197507131998031003',
                'jabatan_petugas' => 'Kepala Pangkalan PSDKP Lampulo',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:04:24',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 3,
                'nama' => 'PANGKALAN PSDKP BITUNG',
                'code' => '002',
                'alamat1' => 'Jl Tandurusa Naemundung Kel Aertembaga dua Kec Aertembaga Kota Bitung - Sulawesi Utara',
                'alamat2' => 'Telp. (0438) 2239156  Fax (0438) 36797',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email ',
                'kota' => 'Bitung',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Donny Muhamad Faisal',
                'nip_petugas' => '',
                'jabatan_petugas' => 'Kepala Pangkalan PSDKP Bitung',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2025-02-24 06:51:53',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 4,
                'nama' => 'PANGKALAN PSDKP JAKARTA',
                'code' => '003',
                'alamat1' => 'Jl Muara Baru Ujung Jakarta 14440',
                'alamat2' => 'Telepon (021) 6614712 FaKSIMILI (021) 6614712',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.jakarta@kkp.go.id',
                'kota' => 'Jakarta',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Suwono Darwinto, A.Pi, S.Pi, M.H',
                'nip_petugas' => '',
                'jabatan_petugas' => 'Kepala Pangkalan PSDKP Jakarta',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:05:14',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 5,
                'nama' => 'STASIUN PSDKP BELAWAN',
                'code' => '004',
                'alamat1' => 'Jl. Gabion Belawan - Medan Sumatera Utara 20414',
                'alamat2' => 'Telp (061) 6943047 Fax. (061) 6943134',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id  Email psdkpbelawan@yahoo.co.id',
                'kota' => 'Medan',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Adhi Kurniadi, S.St.Pi',
                'nip_petugas' => '198607122009011003',
                'jabatan_petugas' => 'Ketua Tim Kerja Prasarana,Sarana dan Operasi Kapal',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2024-07-18 21:02:21',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 6,
                'nama' => 'PANGKALAN PSDKP BATAM',
                'code' => '005',
                'alamat1' => 'Jl. Trans Barelang Jembatan II Pulau Nipah Kel. Setokok Kec. Bulang Batam Kep. Riau',
                'alamat2' => 'Telp (0778) 4091708',
                'alamat3' => 'Website : www.djpsdkp.kkp.go.id Email : psdkp.batam@kkp.go.id',
                'kota' => 'Batam',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Sentanu Bekti Sejati Faathirulloh',
                'nip_petugas' => '199601052018011002',
                'jabatan_petugas' => 'Staff Pangkalan PSDKP Batam',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-11-26 22:02:49',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 7,
                'nama' => 'STASIUN PSDKP PONTIANAK',
                'code' => '006',
                'alamat1' => 'Jl. Dr Moh Hatta Desa Sungai Rengas Kec Sungai Kakap Kab. Kuburaya, KalBar 78381',
                'alamat2' => 'Telp (0561) 773321 Fax (0561) 773321',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.pontianak@kkp.go.id',
                'kota' => 'Pontianak',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Erik Sostenas S.St.Pi, M.Si',
                'nip_petugas' => '198503162007011006',
                'jabatan_petugas' => 'Kepala Pangkalan PSDKP Pontian',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:06:04',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 8,
                'nama' => 'STASIUN PSDKP CILACAP',
                'code' => '007',
                'alamat1' => 'Jl. Bima No. 104 A Kel. Kebon Manis Kec, Cilacap Utara Kab. Cilacap Jawa Tengah 53235',
                'alamat2' => 'Telp. (0282) 5565152 Fax (0282) 5565152',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.cilacap@kkp.go.id',
                'kota' => 'Cilacap',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Moh Nuh Hudawi S.Pi',
                'nip_petugas' => '197912192009121001',
                'jabatan_petugas' => 'Kepala Stasiun PSDKP Cilacap',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:06:33',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 9,
                'nama' => 'STASIUN PSDKP TARAKAN',
                'code' => '008',
                'alamat1' => 'Jl. Aki Balak Kel Karang Harapan Kec. Tarakan Barat Kota Tarakan 77111',
                'alamat2' => 'Telp. (0551) 3826321 Fax (0551) 3826321',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.tarakan@kkp.go.id',
                'kota' => 'Tarakan',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => 'Akhmadon',
                'nip_petugas' => '',
                'jabatan_petugas' => 'Kepala Pangkalan PSDKP Tarakan',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:06:55',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 10,
                'nama' => 'PANGKALAN PSDKP BENOA',
                'code' => '009',
                'alamat1' => 'Jl. Raya Pelabuhan Umum Benoa Denpasar Selatan Bali 80223',
                'alamat2' => 'Telp. (0361) 4480308 Fax (0361) 4480308 ',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.benoa@kkp.go.id',
                'kota' => 'Denpasar',
                'zona_waktu_upt' => 'WITA',
                'nama_petugas' => 'Ndaru Ismiarto, S.IP, M.M',
                'nip_petugas' => '',
                'jabatan_petugas' => 'Kepala Pangkalan PSDKP Benoa',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:07:17',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 11,
                'nama' => 'STASIUN PSDKP KUPANG',
                'code' => '010',
                'alamat1' => 'Jl. Yos Sudarso Jurusan Bolok Kel. Alak Kec. Alak Kupang NTT 85231',
                'alamat2' => 'Telp. (0380) 890456  Fax. (0380) 890456',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.kupang@kkp.go.id',
                'kota' => 'Kupang',
                'zona_waktu_upt' => 'WITA',
                'nama_petugas' => 'Rihat Hutahayan, A.Md.Pi',
                'nip_petugas' => '198907272018011003',
                'jabatan_petugas' => 'Staf Stasiun PSDKP Kupang',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2024-03-21 21:06:17',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 12,
                'nama' => 'PANGKALAN PSDKP TUAL',
                'code' => '011',
                'alamat1' => 'Jalan Bukit Dumar Nomor 1 Komplek PPN Tual - Kota Tual 97651',
                'alamat2' => 'Telepon (0916) 21606, Faksimile (0916) 21696',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.tual@kkp.go.id',
                'kota' => 'Tual',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => '',
                'nip_petugas' => '',
                'jabatan_petugas' => '',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:07:59',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 13,
                'nama' => 'STASIUN PSDKP AMBON',
                'code' => '012',
                'alamat1' => 'Jl. Sultan Hasanudin Kmp. Pelabuhan Perikanan Nusantara Ambon 97128 ',
                'alamat2' => 'Telepon (0911) 351783 Fax. (0911) 351781',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.ambon@kkp.go.id',
                'kota' => 'Ambon',
                'zona_waktu_upt' => 'WIT',
                'nama_petugas' => 'Hariym Raya Maharohakti',
                'nip_petugas' => '',
                'jabatan_petugas' => 'Kepala Pangkalan PSDKP Ambon',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:08:19',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 14,
                'nama' => 'STASIUN PSDKP BIAK',
                'code' => '013',
                'alamat1' => 'Jl. Adibai Km. 6,5 Sumberker Distrik Samofa Kab. Biak Numfor Papua 98156',
                'alamat2' => 'Telp. (0981) 8211818',
                'alamat3' => 'Website www.djpsdkp.kkp.go.id Email psdkp.biak@kkp.go.id',
                'kota' => 'Biak Numfor',
                'zona_waktu_upt' => 'WIT',
                'nama_petugas' => 'Edi Purnomo, S.St.Pi, M.Si',
                'nip_petugas' => '198406222009011004',
                'jabatan_petugas' => 'Kepala Stasiun PSDKP Biak',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:08:39',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 15,
                'nama' => 'STASIUN PSDKP TAHUNA',
                'code' => '014',
                'alamat1' => 'Jl Boulevard Tahuna Kec Tahuna Timur Kab. Kepulauan Sangihe 95814',
                'alamat2' => 'Telepon (0432) 24425',
                'alamat3' => 'Website : www.djpsdkp.kkp.go.id Email : psdkp.tahuna@kkp.go.id',
                'kota' => '',
                'zona_waktu_upt' => 'WITA',
                'nama_petugas' => 'Amiruddin, A.Md',
                'nip_petugas' => '198008202003121004',
                'jabatan_petugas' => 'Staf Sarpras Pangkalan PSDKP Bitung',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2020-12-18 13:09:03',
                'user_update' => 'admin'
            ],
            [
                'm_upt_id' => 16,
                'nama' => 'DIREKTORAT PENGENDALIAN OPERASI ARMADA',
                'code' => '015',
                'alamat1' => 'Jalan Medan Merdeka Timur No. 16 Gedung Mina Bahari IV Lt 12 Jakarta Pusat 10110',
                'alamat2' => 'Kotak Pos 4130 JKP Telepon (021) 3519070 (Hunting) Faksimil (021) 3520346',
                'alamat3' => 'Website : www.djpsdkp.kkp.go.id E-mail : ditjenpsdkp@kkp.go.id',
                'kota' => 'Jakarta',
                'zona_waktu_upt' => 'WIB',
                'nama_petugas' => '',
                'nip_petugas' => '',
                'jabatan_petugas' => 'Staf Pangkalan',
                'pangkat_petugas' => '',
                'date_insert' => null,
                'user_insert' => null,
                'date_update' => '2024-03-15 14:05:22',
                'user_update' => 'admin'
            ]
        ];

        foreach ($upts as $upt) {
            DB::table('m_upt')->insert($upt);
        }
    }
}
